package enums;

public enum Retorno {
	URL, CORPO, STATUS, CAMINHOAPK, DEVICEID, VERSAODOSO, APPWAITACTIVITY, CAMINHODASFEATURES,
	CAMINHOARQUIVORELATORIOJSON, CAMINHOARQUIVORELATORIOXML, CAMINHODASFEATURESWEBMOBILE, PACOTESTEPS,
	QUANTIDADEDEEXECUCOESEMPARALELO, MASSA;
}